print("Puxa, você foi enforcado!")
print("    _______________         ")
print("   /               \       ")
print("  /                 \      ")
print(" /                   \  ")
print(" |   XXXX     XXXX   |   ")
print(" |   XXXX     XXXX   |    ")
print(" |   XXX       XXX   |      ")
print(" |                   |      ")
print(" \__      XXX      __/     ")
print("   |\     XXX     /|       ")
print("   | |           | |        ")
print("   | I I I I I I I |        ")
print("   |  I I I I I I  |        ")
print("   \_             _/       ")
print("     \_         _/         ")
print("       \_______/           ")
